base_url: http://localhost
custom_instance_pg_databases:
  user_pwd: 0b7386f6-052f-4b06-a3e9-637e4652cf5f
custom_tags:
  - chromium
jwt_secret: tp1D1bVZ6QDVCkYgcAKvdm3wgU64Jnpr
oauths:
  kanidm:
    id: ""
    secret: ""
    connect_config:
      auth_url: /ui/oauth2
      token_url: /oauth2/token
      scopes:
        - openid
        - profile
        - email
    login_config:
      auth_url: /ui/oauth2
      token_url: /oauth2/token
      userinfo_url: /oauth2/openid//userinfo
      scopes:
        - openid
        - profile
        - email
  keycloak:
    id: windmill-client
    secret: bphDuSDVgNBmgdqkMcvc8OfRyEVFCDuc
    display_name: " Windmill"
    connect_config:
      auth_url: http://192.168.1.73:8080/realms/windmill/protocol/openid-connect/auth
      token_url: http://192.168.1.73:8080/realms/windmill/protocol/openid-connect/token
      scopes:
        - openid
        - offline_access
    login_config:
      auth_url: http://192.168.1.73:8080/realms/windmill/protocol/openid-connect/auth
      token_url: http://192.168.1.73:8080/realms/windmill/protocol/openid-connect/token
      userinfo_url: http://192.168.1.73:8080/realms/windmill/protocol/openid-connect/userinfo
      scopes:
        - openid
        - offline_access
retention_period_secs: 2592000
uv_index_strategy: unsafe-best-match
