base_url: http://localhost
custom_instance_pg_databases:
  user_pwd: __SENSITIVE_AND_UNCHANGED__
custom_tags:
  - chromium
jwt_secret: __SENSITIVE_AND_UNCHANGED__
oauths:
  keycloak:
    id: windmill-client
    secret: __SENSITIVE_AND_UNCHANGED__
    display_name: Keycloak
    connect_config:
      auth_url: http://keycloak.local/realms/windmill/protocol/openid-connect/auth
      token_url: http://keycloak.local/realms/windmill/protocol/openid-connect/token
      scopes:
        - openid
        - offline_access
    login_config:
      auth_url: http://keycloak.local/realms/windmill/protocol/openid-connect/auth
      token_url: http://keycloak.local/realms/windmill/protocol/openid-connect/token
      userinfo_url: http://keycloak.local/realms/windmill/protocol/openid-connect/userinfo
      scopes:
        - openid
        - offline_access
    org: http://keycloak.local/realms/windmill
retention_period_secs: 2592000
uv_index_strategy: unsafe-best-match